n = input('Digite algo: ')
print('')

print('N é um número?',n.isalnum())
print('N é numérico?', n.isnumeric())
print('N é decimal?', n.isdecimal())
print('N é alfanumérico?', n.isalnum())
print('N é alfabético?', n.isalpha())
print('N é um dígito?', n.isdigit())
print('N é título?', n.istitle())
print('N é identificador?', n.isidentifier())
print('N está em caixa baixa?', n.islower())
print('N está em caixa alta?', n.isupper())
print('N é imprimível?', n.isprintable())
print('N é um espaço?', n.isspace())
